### ISSUE TITLE
关于node端渲染

### ISSUE THREAD

**Issue by xingbofeng** [aximario/vue-player#1]
同样想通过做一个音乐播放器学习vue技术栈。阅读您的代码，没有找到node服务端请求网易云API的部分代码，想问一下服务端入口文件在哪里，如何通过node端请求网易云API解决跨域问题？

**Comment by aximario** [comment]
这是vue1写的，你想写的话推荐用vue2来写，请求网易云API的方法你可以去搜索网易云API相关的关键词，服务端代码没有开源，因为涉及到了数据库和云存储的一些信息。

**Comment by xingbofeng** [comment]
好的，谢谢，已经尝试了，不过搜出来的api只返回一条结果。。
